name: anime_archive

description: "Anime Scene Search Engine App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: 2.2.6
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  rflutter_alert: ^2.0.7
  flutter_spinkit: ^5.2.0
  dio: ^5.4.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Lexend_Mega
      fonts:
        - asset: assets/Lexend_Mega/static/LexendMega-Black.ttf
        - asset: assets/Lexend_Mega/static/LexendMega-Bold.ttf
        - asset: assets/Lexend_Mega/static/LexendMega-ExtraBold.ttf
        - asset: assets/Lexend_Mega/static/LexendMega-ExtraLight.ttf
        - asset: assets/Lexend_Mega/static/LexendMega-Light.ttf
        - asset: assets/Lexend_Mega/static/LexendMega-Medium.ttf
        - asset: assets/Lexend_Mega/static/LexendMega-Regular.ttf
        - asset: assets/Lexend_Mega/static/LexendMega-SemiBold.ttf
        - asset: assets/Lexend_Mega/static/LexendMega-Thin.ttf